### ISSUE TITLE
java.lang.NoClassDefFoundError: com/microsoft/pnp/log4j/LoggingConfiguration

### ISSUE THREAD

**Issue by tanzencoder** [mspnp/azure-databricks-streaming-analytics#11]
I am walking through this sample and I have run into the following error when trying to create the job. 

ERROR Uncaught throwable from user code: java.lang.NoClassDefFoundError: com/microsoft/pnp/log4j/LoggingConfiguration
	at com.microsoft.pnp.TaxiCabReader$$anonfun$main$2.apply(TaxiCabReader.scala:22)
	at com.microsoft.pnp.TaxiCabReader$$anonfun$main$2.apply(TaxiCabReader.scala:21)
	at com.microsoft.pnp.TryWith$$anonfun$apply$2.apply(TryWith.scala:10)
	at com.microsoft.pnp.TryWith$$anonfun$apply$2.apply(TryWith.scala:8)
	at scala.util.Success.flatMap(Try.scala:231)

I am assuming that it is not loading the azure-databricks-monitoring-0.9.jar but I am having difficulty determining the cause. I have turned on init logging to trouble shoot but the files are empty (appears that the echo statements are not firing). Any guidance on where to look would be greatly appreciated.

**Comment by hallihan** [comment]
It looks like there were some changes on the Azure Databricks side for library jars.  If you follow the instructions updated in #15 you should not see this error.
